### ISSUE TITLE
Update own profile

### ISSUE THREAD

**Issue by Mkmarie** [apolloeleven/agora-yii2-vue#11]
Four Modals that a user should be able to update:

Profile Image> Choose Image/ Remove
Account > Email, Password, Confirm Password
Information > First Name, Last Name, Phone, Mobile Phone, Birthday, Hobby and About Me rich text box

There will be an “Update” button at the top of the page

**Comment by Mkmarie** [comment]
Leave only these fields: First Name, Last Name, Phone, Mobile Phone, Birthday, Hobby and About Me rich text box

**Comment by thecodeholic** [comment]
Most of the things are done and merged to master.
The only things that needs to be done is removing avatar and validate password strength.
