### ISSUE TITLE
Workspace CRUD

### ISSUE THREAD

**Issue by Sopho1988** [apolloeleven/agora-yii2-vue#14]
1. A Workspace Admin or a superuser should be able to add a new workspace.

The workspace section should be on the left-hand side 

My Workspaces
   XYZ
   ABC
   ETC

2. Clicking on My Workspaces the section will display the workspaces I'm a  member of. The workspaces will be displayed as provided in the screenshot. The user with the permission to add a new workspace will be able to see the workspace button(as provided in the screenshot)
The workspace can be edited or deleted in the same section through 3 dots nested on the individual workspace image. 

3. Add/edit modal and its fields :
Image import section > Choose Image; Remove

- Enable create folders inside folders checkbox
- Name of the workspace.
- Abbreviation
- Description (free text box) 
- Cancel and Submit buttons
Clicking on the workspace image should redirect you to the inner view of the particular workspace.

4. Inner view of the workspace: (Discuss it with together.)

- Icon for "Users" I should be able to see users by just hovering over it, but if I want to make the view static, I could be able to click on the icon, which then I can close by the X button.

"Need to discuss the visual arrangement of the inner view."

There will be 2 sections on the page, one for the timeline and the second for the folders created under the workspace. 

The timeline will be of the same visual + "Write on Timeline" button.
It should be scrollable.

The folders will occupy the second section of the view, 2 rows max. - this should be discussed. 

I should be able to go to see the folder items just by clicking on it. There will be 2 sections, the list of articles on the left-hand side, the other section will be occupied by attachments.

"Create new article" button. The added article will include just a thumbnail of the article description. If I click on the article title, I should go to the actual article view on a different page, where I can read the whole article and can be reacted/commented by users. 

The articles should be only displayed in a limited number, which is controlled by drop-down at the bottom of the article list, with the selections of max(5, 10, 20, 100 items per view)
The same view will include an attachment section as was on the parent view.

-Go back button where needed
-Breadcrumbs where needed. 
-Add to favorite where needed. If I click on it, the section/view will be displayed under the workspace items as a shortcut link. Undo will revert it to the default. 

Note to self:  need to copy descriptions under their relevant issues on Monday

![Minitube Intranet 9-18-2020 7-48-13 PM](https://user-images.githubusercontent.com/71025372/93618297-1fd4f380-f9e8-11ea-8bf3-f4873e1a0292.png)

![Minitube Intranet 9-21-2020 8-42-33 PM](https://user-images.githubusercontent.com/71025372/93795816-fbc51c80-fc4a-11ea-9528-d7e4d565978f.png)

**Comment by Mkmarie** [comment]
1 day
