### ISSUE TITLE
Add download button on the file preview window

### ISSUE THREAD

**Issue by isvanidze2** [apolloeleven/agora-yii2-vue#144]
![image](https://user-images.githubusercontent.com/24476804/99704445-d79e8400-2ab1-11eb-9e7a-73ae15ba879b.png)
### What steps will reproduce the problem?
In the file manager press on the file name to open the file preview window
### What's expected?
File download button
### What do you get instead?
There is no file download button

**Comment by thecodeholic** [comment]
@isvanidze2 What do you think if we put the button next to the "Next" button, not in the modal header...
