### ISSUE TITLE
Folder CRUD

### ISSUE THREAD

**Issue by Sopho1988** [apolloeleven/agora-yii2-vue#15]
Location:  Workspace main page > Create New Folder

A new folder can be added or edited by a workspace admin and an admin only

Add/Edit folder > Module view:
-Title when adding a new article: Create New Artice; Title when editing an existing article
-Image upload filed (Choose Image/ Remove)
-"Title" - of the folder
-An open text box for "Description"

Articles can be created within the folder as well as attachments are able to provide within the file.

The folder CRUD is of a 5 level tree hierarchy, so I should be able to create a folder(s) under a folder. 

The folder inner page will be split into three sections: Articles, Folders, Attachments

**Comment by Mkmarie** [comment]
1 day
