### ISSUE TITLE
There is no possibility to see who liked the post

### ISSUE THREAD

**Issue by isvanidze2** [apolloeleven/agora-yii2-vue#150]
![image](https://user-images.githubusercontent.com/24476804/99707839-6f9e6c80-2ab6-11eb-8ae7-4de97586be0a.png)

**Comment by thecodeholic** [comment]
Along with the post we need to return user list who liked the post

**Comment by thecodeholic** [comment]
And we need to display this list in popover
https://bootstrap-vue.org/docs/directives/popover#popovers
