### ISSUE TITLE
Post attachment view is not working

### ISSUE THREAD

**Issue by isvanidze2** [apolloeleven/agora-yii2-vue#151]
### What steps will reproduce the problem?
Click on the attached image of the post

### What's expected?
Open file view window

### What do you get instead?
Nothing is happening

**Comment by thecodeholic** [comment]
When Image is uploaded on timeline, it must be resized to smaller width (680px) and converted into webp image.
When clicking on image on timeline it should open original image on fullscreen.

**Comment by thecodeholic** [comment]
If you upload an image in portrait mode, when it is converted into webp it is displayed as landspace image.
