### ISSUE TITLE
Article CRUD

### ISSUE THREAD

**Issue by Sopho1988** [apolloeleven/agora-yii2-vue#16]
Location: Workspace > a folder's inner view > "Create new article"

Clicking on the "Create new article button" will open a pop up modal similar to "Create new folder"

- Image section with a drag and drop option and Choose Image buttons. Add the remove button next to it.
- Input filed for a Title
- Open textbox for a description
- Cancel and Submit buttons

 The added article will include just a thumbnail of the article description. If I click on the article title, I should go to the actual article view on a different page, where I can read the whole article and can be reacted/commented by users.

**Comment by Mkmarie** [comment]
1 day
