### ISSUE TITLE
Attachment CRUD

### ISSUE THREAD

**Issue by Sopho1988** [apolloeleven/agora-yii2-vue#17]
The first header level:
Upload Button, Columns?; Share, Delete, Technical Note

The second row with column headers:

Checkbox(without header), Name of the file, Size, Updated at, Updated by, Actions 

Actions > Edit Label, Download, Share (count of shares), Delete

I should be able to delete just by ticking a file or multiple files and click on the delete button on the fist level headers, or individually delete a file through the actions button. 

Only workspace admin and admin should be able to upload for all types of files. The videos can be also uploaded there. A non-playable video format should be able to convert into a playable format.

**Comment by Mkmarie** [comment]
2 days
