### ISSUE TITLE
Posting on timeline

### ISSUE THREAD

**Issue by Sopho1988** [apolloeleven/agora-yii2-vue#18]
Location > Dashboard and a Workspace inner page 
"Write on the timeline" button on the left-hand side. 
The fields: A dropdown for Workspaces "Please Select Workspace".
Select Image or Video file (to browse files) and drag and drop as well
Description -an open text box
Cancel and Submit buttons with their respective functions.

If a post is added from a timeline, I should be able to select a workspace. If I add a post from the workspace, the workspace drop-down field isn't necessary.

I should be able to delete and edit a post when clicking on three dots at the top of the post, on the left hand side. 
![Minitube Intranet 9-18-2020 7-31-31 PM](https://user-images.githubusercontent.com/71025372/93616786-3b3eff00-f9e6-11ea-8f8b-45390a17c010.png)

**Comment by Mkmarie** [comment]
Dashboard > "Write on timeline" button. 
The fields: A dropdown for Workspaces "Please Select Workspace".
Select Image or Video file (to browse files)
Description -a free text box

Cancel and Submit buttons with their respective functions.

![Minitube Intranet 9-18-2020 7-31-31 PM](https://user-images.githubusercontent.com/71025372/93616262-90c6dc00-f9e5-11ea-938b-2d8db2506035.png)

**Comment by Mkmarie** [comment]
1 day
