### ISSUE TITLE
Sharing on timeline

### ISSUE THREAD

**Issue by Sopho1988** [apolloeleven/agora-yii2-vue#19]
Timeline Locations:
Dashboard and Inner page of the Workspace.

The dashboard will be split into three vertical sections - "Latest Updates on News and Events", "My Timeline - Latest Updates", "My Workspace - Latest Updates"

Add one giant scroll for the page. 

I should be able to share attachments, and articles.

Attachments > add a share button similar to the screenshot, but prefer to discuss it.
- Checking an attachment should enable the share button. After clicking on that, a modal should pop up with an open text box, asking "Would you like to share this on your workspace timeline"?
- There will be a title "Add a comment" above the open text box. 
- When I share it, the shared document should be displayed on my timeline within that specific workspace and on the dashboard as the latest update. 

The visual of the shared document:
- A profile picture of the user
- The text "A user XYZ uploaded an attachment to an article ABC" - this requires to be discussed.

Sharing of an article:
- There will be a share button similar to attachments. Next to the share button, please add a count of the article shares. When I click on the share button, the same window will pop up similar to attachments. Again, I should be able to see my shared item under my timelines. 

![Minitube Intranet 9-21-2020 9-07-53 PM](https://user-images.githubusercontent.com/71025372/93798317-84918780-fc4e-11ea-94ec-b1a110d6931f.png)

**Comment by Mkmarie** [comment]
1 day
