### ISSUE TITLE
Writing comments on articles/timeline posts

### ISSUE THREAD

**Issue by Sopho1988** [apolloeleven/agora-yii2-vue#20]
The comment section will be the same for articles and timeline posits:
- A comment input box with the comment button.
- Emoji location
- Below an article > Like button which in case if I activate will like the post. The same icon should display the count of the linkes on a post. 
- We should also display a number of comments on a post.
- The comment section will be a two-level tree structure when replying to a comment. After that, the reply will include the mention feature. 
- edit and delete features. 
- Micro profile picture >name of the commenter(this will be a hyperlink to a user profile) comment > comment time (Discuss it together)

**Comment by Mkmarie** [comment]
1 day
