### ISSUE TITLE
Like on articles/timeline posts

### ISSUE THREAD

**Issue by Sopho1988** [apolloeleven/agora-yii2-vue#21]
- Emoji clickthrough icon. when I hover over it, the text will pop up - Choose an emoji (In the new version of Unicode, there is a bunch of emoji symbols.  We can use either Google emojis or Twitter emojis as a source)
- Like button besides liking a post should display the count of the likes on a post. 
- After I click on like, the button should color code into a darker color to notify me that the button was successfully activated

**Comment by Mkmarie** [comment]
1 day
