### ISSUE TITLE
Setup > Departments

### ISSUE THREAD

**Issue by Mkmarie** [apolloeleven/agora-yii2-vue#7]
![Org Chart (1)](https://user-images.githubusercontent.com/71025372/93203242-2142b980-f765-11ea-8cac-2e570ae2ade2.png)
Add a new section on the left-hand side below workspaces. The Setup is only accessible to Admin.

The only sub-menu item at the moment will be "Departments" 

The Department hierarchy will be a Tree.

Departments should be able to drag and drop under a parent/child department

Add Department should be inside the inner section of the module

**Comment by thecodeholic** [comment]
When parent department is about to be deleted if it has children we must show correct error.
