### ISSUE TITLE
Data alteration on the Edit Form after submit

### ISSUE THREAD

**Issue by Mkmarie** [apolloeleven/agora-yii2-vue#85]
Clicking on a submit button under a workspace edit modal, unchecks the "Enable creating folders inside folders" button and throws a required field error on a "Name" field for a second before the modal get's closed, although nothin is changed on the edit form after reopening it.

**Comment by saiat3** [comment]
This issue is being closed because there is no more `Enable creating folders inside folders` checkbox in workspace modal, therefore it can not be reproduced. If some other variation of this bug is present, new issue should be created.
