### ISSUE TITLE
Workspace Modifications

### ISSUE THREAD

**Issue by Mkmarie** [apolloeleven/agora-yii2-vue#86]
1. Add a file manager under a workspace
2. Uploaded file can be liked and commented in the following way "Like(Unlike)/Comment(2). These Comment should be a pop up modal link with the comment input field. I should be able to attach a file too and like or reply after post my comment and the attachment. The Modal will display a comment history every time I open it.

**Comment by thecodeholic** [comment]
I am closing this issue, because we have already done file manager according to another issue and we don't do like and comment on files at the moment.
